# Generated by Django 4.1.7 on 2023-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_profile_birth_date_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to=''),
        ),
    ]
