# Generated by Django 4.1.7 on 2023-06-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='to_subscribe',
            new_name='to_subscriber',
        ),
    ]
