# Generated by Django 4.1.7 on 2023-06-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_rename_to_subscribe_subscription_to_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='profiles',
            new_name='profile',
        ),
    ]
