# Generated by Django 4.1.7 on 2023-06-29 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_profiles_chat_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='profile',
        ),
        migrations.AddField(
            model_name='chat',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend', to='network.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='you',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='you', to='network.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 15, 37, 0, 97500, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/media/images/default.jpg', upload_to=''),
        ),
    ]
