# Generated by Django 4.1.7 on 2023-06-29 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_chat_profile_chat_friend_chat_you_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 15, 42, 48, 136359, tzinfo=datetime.timezone.utc)),
        ),
    ]
