# Generated by Django 4.1.7 on 2023-06-29 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_chat_name_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_room', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='you',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='you_room', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 15, 50, 8, 588200, tzinfo=datetime.timezone.utc)),
        ),
    ]
