# Generated by Django 4.1.7 on 2023-06-29 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_chat_friend_alter_chat_you_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 17, 10, 27, 239969, tzinfo=datetime.timezone.utc)),
        ),
    ]
