# Generated by Django 4.1.7 on 2023-07-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/media/images/default.jpg', upload_to='photo'),
        ),
    ]
