# Generated by Django 4.1.7 on 2023-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_post_like_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
