# Generated by Django 4.1.7 on 2023-07-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_photo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_room', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='you',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='you_room', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='network.profile'),
        ),
    ]
