# Generated by Django 4.1.7 on 2023-07-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_alter_chat_friend_alter_chat_you_alter_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='to_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_subscribers', to='network.profile'),
        ),
    ]
