# Generated by Django 4.1.7 on 2023-07-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_alter_subscription_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_room', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='you',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='you_room', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='to_subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_subscribers', to='network.profile'),
        ),
    ]
