# Generated by Django 4.1.7 on 2023-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_remove_photo_comment_support_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
