# Generated by Django 4.1.7 on 2023-07-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_alter_support_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to='network.profile'),
        ),
    ]
