# Generated by Django 4.1.7 on 2023-07-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_alter_comment_photo_alter_comment_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.photo'),
        ),
    ]
