# Generated by Django 4.1.7 on 2023-07-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_alter_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='support',
            name='text',
            field=models.TextField(),
        ),
    ]
