# Generated by Django 4.1.7 on 2023-07-04 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0032_alter_support_user_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='user_support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support', to=settings.AUTH_USER_MODEL),
        ),
    ]
