# Generated by Django 4.1.7 on 2023-07-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_alter_support_user_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='creation_user_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
