# Generated by Django 4.1.7 on 2023-07-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0034_support_creation_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user_support',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to=settings.AUTH_USER_MODEL),
        ),
    ]
