# Generated by Django 4.1.7 on 2023-07-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_all_music_my_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_music',
            name='sound',
            field=models.FileField(upload_to='music'),
        ),
    ]
