# Generated by Django 4.1.7 on 2023-07-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_alter_all_music_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_list',
            field=models.ManyToManyField(related_name='like_lists', to='network.profile'),
        ),
    ]
