# Generated by Django 4.1.7 on 2023-07-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_comment_like_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='like_list',
            field=models.ManyToManyField(related_name='like_photos', to='network.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_list',
            field=models.ManyToManyField(related_name='like_posts', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_list',
            field=models.ManyToManyField(related_name='like_comments', to='network.profile'),
        ),
    ]
